[package]
name = "edtear"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
couch_rs = "0.11.0"
ctrlc = "3.4.5"
#diesel = { version = "2.2.5", features = ["postgres", "sqlite"] }
dotenvy = "0.15.7"
env_logger = "0.11.5"
log = "0.4.22"
miniz_oxide = "0.8.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["full"] }
zmq = "0.10.0"
