services:
  postgres:
    image: "postgis/postgis:16-3.5-alpine"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    # Non-default port so we don't interfere with system Postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: edtear
    # This will contain our password
    env_file: "postgres.env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  edtear:
    build: .
    env_file: "postgres.env"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

volumes:
  postgres-data:
